In [1]:
import pandas as pd

clean_df = pd.read_csv("../data/processed/clean_metadata.csv")

print(clean_df.head())

             file_name  platform                              hash
0  grinning_face_0.png     Apple  942f08f8aa7633a121c2e0fcab07ccf4
1  grinning_face_0.png    Google  f455777ecf02123d414289a13a0410a9
2  grinning_face_0.png  Facebook  e1c39c086044c2432ce552dd2465385c
3  grinning_face_0.png   Windows  8e6b7cafc0ea40d81f9cfe264baced8c
4  grinning_face_0.png   Twitter  e78e35bed487156d11da770a0f2ccccb

In [2]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    clean_df,
    test_size=0.30,
    stratify=clean_df["platform"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["platform"],
    random_state=42
)

print(len(train_df), len(val_df), len(test_df))

8400 1800 1801

In [3]:
print(train_df["platform"].value_counts())
print(val_df["platform"].value_counts())
print(test_df["platform"].value_counts())

platform
JoyPixels    1266
Twitter      1264
Apple        1262
Google       1261
Facebook     1185
Samsung      1167
Windows       995
Name: count, dtype: int64
platform
Twitter      271
JoyPixels    271
Apple        270
Google       270
Facebook     254
Samsung      251
Windows      213
Name: count, dtype: int64
platform
JoyPixels    272
Apple        271
Twitter      271
Google       270
Facebook     254
Samsung      250
Windows      213
Name: count, dtype: int64

In [4]:
import os
import shutil

In [5]:
base_path = "../data/final"

for split in ["train", "val", "test"]:
    for platform in clean_df["platform"].unique():
        os.makedirs(
            f"{base_path}/{split}/{platform}",
            exist_ok=True
        )

In [6]:
def copy_images(df, split_name):

    for _, row in df.iterrows():

        src = f"../data/processed/{row['platform']}/{row['file_name']}"
        dst = f"../data/final/{split_name}/{row['platform']}/{row['file_name']}"

        shutil.copy(src, dst)

In [7]:
copy_images(train_df, "train")
copy_images(val_df, "val")
copy_images(test_df, "test")

print("Done")

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/JoyPixels/kiss:_man,_man_468.png'

In [8]:
import os

test_path = "../data/processed/JoyPixels/kiss:_man,_man_468.png"

print(os.path.exists(test_path))

True

In [9]:
missing_files = []

for _, row in clean_df.iterrows():

    path = f"../data/processed/{row['platform']}/{row['file_name']}"

    if not os.path.exists(path):
        missing_files.append(path)

print("Missing files:", len(missing_files))

Missing files: 0

In [10]:
missing_files[:20]

[]

In [11]:
print(len(clean_df))
print(len(train_df) + len(val_df) + len(test_df))

12001
12001

In [12]:
problem_row = clean_df[
    clean_df["file_name"].str.contains("kiss", na=False)
]

problem_row.head(10)

                      file_name   platform                              hash
112  face_blowing_a_kiss_16.png      Apple  cc04bd6bf1d61c2ed3f750a871e389ea
113  face_blowing_a_kiss_16.png     Google  3080d62a957882c0782eafc3d06549e0
114  face_blowing_a_kiss_16.png   Facebook  b3b0a8488a6d3167258ce4b8a6eac553
115  face_blowing_a_kiss_16.png    Windows  69af52ecd06197b3744bd8cc367bb020
116  face_blowing_a_kiss_16.png    Twitter  1e2fb91d0ecad713c5bdac6e024f1a1c
117  face_blowing_a_kiss_16.png  JoyPixels  55217c612af695abea41b4645ebb323b
118  face_blowing_a_kiss_16.png    Samsung  2387300709ca954432b8db97135759e6
119         kissing_face_17.png      Apple  58fa2114a5999a811b97862efbc13c29
120         kissing_face_17.png     Google  fa1b09b0ee16ed748847d5a270d19cb1
121         kissing_face_17.png   Facebook  13265e2bdc7740358a602f5ce7e8d362

In [13]:
import os

joy_files = os.listdir("../data/processed/JoyPixels")

# נראה קבצים עם kiss
[f for f in joy_files if "kiss" in f][:20]

['face_blowing_a_kiss_16.png',
 'kiss',
 'kissing_cat_112.png',
 'kissing_face_17.png',
 'kissing_face_with_closed_eyes_19.png',
 'kissing_face_with_smiling_eyes_20.png',
 'kiss_466.png',
 'kiss_mark_119.png']

In [14]:
path = "../data/processed/JoyPixels/kiss:_man,_man_468.png"

print(path)
print(os.path.exists(path))

../data/processed/JoyPixels/kiss:_man,_man_468.png
True

In [16]:
import shutil
import os

def copy_images(df, split_name):

    copied = 0
    missing = []

    for _, row in df.iterrows():

        src = f"../data/processed/{row['platform']}/{row['file_name']}"
        dst = f"../data/final/{split_name}/{row['platform']}/{row['file_name']}"

        try:
            shutil.copy(src, dst)
            copied += 1

        except Exception as e:
            missing.append((src, str(e)))

    print("Copied:", copied)
    print("Errors:", len(missing))

    return missing

In [17]:
errors = copy_images(train_df, "train")
errors[:5]

Copied: 7064
Errors: 1336

[('../data/processed/JoyPixels/kiss:_man,_man_468.png',
  "[Errno 2] No such file or directory: '../data/processed/JoyPixels/kiss:_man,_man_468.png'"),
 ('../data/processed/JoyPixels/flag:_Algeria_1619.png',
  "[Errno 2] No such file or directory: '../data/processed/JoyPixels/flag:_Algeria_1619.png'"),
 ('../data/processed/Apple/person:_beard_214.png',
  "[Errno 2] No such file or directory: '../data/processed/Apple/person:_beard_214.png'"),
 ('../data/processed/Facebook/flag:_Russia_1751.png',
  "[Errno 2] No such file or directory: '../data/processed/Facebook/flag:_Russia_1751.png'"),
 ('../data/processed/JoyPixels/flag:_French_Southern_Territories_1777.png',
  "[Errno 2] No such file or directory: '../data/processed/JoyPixels/flag:_French_Southern_Territories_1777.png'")]

In [18]:
import os

valid_rows = []

for _, row in clean_df.iterrows():

    path = f"../data/processed/{row['platform']}/{row['file_name']}"

    if os.path.exists(path):
        valid_rows.append(row)

valid_df = pd.DataFrame(valid_rows)

print("Original:", len(clean_df))
print("Valid files:", len(valid_df))
print("Removed:", len(clean_df) - len(valid_df))

Original: 12001
Valid files: 12001
Removed: 0

In [19]:
valid_df.to_csv(
    "../data/processed/final_clean_metadata.csv",
    index=False
)

In [20]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    valid_df,
    test_size=0.30,
    stratify=valid_df["platform"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["platform"],
    random_state=42
)

print(len(train_df), len(val_df), len(test_df))

8400 1800 1801

In [21]:
import re

def clean_filename(name):
    return re.sub(r'[<>:"/\\|?*]', '_', name)

In [22]:
print("Original:", len(clean_df))
print("Valid files:", len(valid_df))
print("Removed:", len(clean_df) - len(valid_df))

Original: 12001
Valid files: 12001
Removed: 0

In [23]:
row = train_df[
    train_df["file_name"].str.contains("kiss", na=False)
]

row.head(10)

,file_name,platform,hash
123,kissing_face_17.png,Twitter,1ac64eef6e87cb581dd5f56e2531f5f6
3032,"kiss:_man,_man_468.png",JoyPixels,f58eda3534571adb0ad0955b23a91f8d
3025,"kiss:_woman,_man_467.png",Twitter,ab264c02e2d5ffc80624e42704c5a890
3029,"kiss:_man,_man_468.png",Facebook,0050505d054b3fade1653ea744a127cd
138,kissing_face_with_closed_eyes_19.png,JoyPixels,6c7609c087b87600684328a1b3da3030
3019,kiss_466.png,Twitter,cedb56df1f9e60a8b61081256a2bebd7
762,kissing_cat_112.png,Facebook,b32db1798f6a3e7f3bf48c5ccf33193e
134,kissing_face_with_closed_eyes_19.png,Google,c4e789b77f8294a1e8200c0683619273
815,kiss_mark_119.png,Samsung,e17076d422c6440e478a8d15850afdb3
3024,"kiss:_woman,_man_467.png",Windows,41d08d62180853944290f2a05f95e992

In [24]:
problem = train_df[
    train_df["file_name"] == "kiss:_man,_man_468.png"
]

print(problem)

                   file_name   platform                              hash
3032  kiss:_man,_man_468.png  JoyPixels  f58eda3534571adb0ad0955b23a91f8d
3029  kiss:_man,_man_468.png   Facebook  0050505d054b3fade1653ea744a127cd
3027  kiss:_man,_man_468.png      Apple  a566778c5f7f308e7410c57450d10ebe
3030  kiss:_man,_man_468.png    Windows  3c2b4fca6666571a0b83372ca5df55e9

In [25]:
import os

path = "../data/processed/JoyPixels/kiss:_man,_man_468.png"

print(os.path.exists(path))

True

In [27]:
joy_files = os.listdir("../data/processed/JoyPixels")

[f for f in joy_files if "468" in f]

[]

In [28]:
path = "../data/processed/JoyPixels/kiss:_man,_man_468.png"
print(os.path.exists(path))

True

In [29]:
path = "../data/processed/JoyPixels/kiss:_man,_man_468.png"

with open(path, "rb") as f:
    print("opened successfully")

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/JoyPixels/kiss:_man,_man_468.png'